POST http://localhost:3333/api/database/analyze-database
content-type: application/json

{
    "connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
		"aliasMap": {
			"tables": {
				"ang_pro": "Mitarbeiter-Projekt-Zuordnungen",
				"angest": "Mitarbeiter",
				"kunde": "Kunden",
				"projekt": "Projekte"
			},
			"columns": {
				"ang_pro": {
					"PROZ_ARB": "Arbeitsanteil in Prozent",
					"PNR": "Projekt-ID",
					"ANGNR": "Mitarbeiter-ID"
				},
				"angest": {
					"ANGNR": "Mitarbeiter-ID",
					"NAME": "Name",
					"WOHNORT": "Wohnort",
					"BERUF": "Berufsbezeichnung",
					"GEHALT": "Gehalt",
					"ABTNR": "Abteilungsnummer"
				},
				"kunde": {
					"KDNR": "Kunden-ID",
					"NAME": "Kundenname",
					"WOHNORT": "Wohnort",
					"TAETIG_ALS": "Tätigkeit"
				},
				"projekt": {
					"PNAME": "Projektname",
					"PNR": "Projekt-ID",
					"P_BESCHR": "Projektbeschreibung",
					"P_LEITER": "Projektleiter (Mitarbeiter-ID)"
				}
			}
		}
}

# {
#     "connectionInfo": {
#         "type": "postgres",
#         "host": "localhost",
#         "port": "5432",
#         "username": "myuser",
#         "password": "mypass",
#         "database": "fussballdb",
#         "schema": "public"
#     }
# }

###
GET http://localhost:3333/api/generation/generate

{
	"connectionInfo": {
		"type": "postgres",
		"host": "localhost",
		"port": "5432",
		"username": "myuser",
		"password": "mypass",
		"database": "fussballdb",
		"schema": "public"
	},
	"taskConfiguration": {
		"aggregation": false,
		"columnCount": 2,
		"predicateCount": 2,
		"operationTypes": [],
		"joinDepth": 2,
		"joinTypes": [],
		"groupby": false,
		"having": false,
		"orderby": true
	}
}

###
POST http://localhost:3333/api/grading/grade
content-type: application/json

{
	"connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
	"gradingRequest": {
		"taskId": "4f7c66ed-e4e5-422e-8d6f-ef4ee3876d02",
		"studentQuery": "SELECT kunde.WOHNORT, COUNT(kunde.KDNR) FROM test.kunde GROUP BY kunde.WOHNORT HAVING COUNT(kunde.KDNR) > 1",
        "referenceQuery": "SELECT * FROM PROJEKT"
	},
	"languageCode": "de",
	"generationStrategy": "template"
}

###
POST http://localhost:3333/api/description/template
content-type: application/json

{
	"connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
	"query": "SELECT kunde.WOHNORT, COUNT(kunde.KDNR) FROM test.kunde GROUP BY kunde.WOHNORT HAVING COUNT(kunde.KDNR) > 1",
	"languageCode": "de"
}