POST http://localhost:3333/api/database/analyze-database
content-type: application/json

{
    "connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
	"aliasMap": {
    "tables": {
        "categories": "Produktkategorien",
        "customer_customer_demo": "Zuordnungen von Kundendemografien",
        "customer_demographics": "Kundendemografien",
        "customers": "Kunden",
        "employees": "Mitarbeiter",
        "employee_territories": "Mitarbeitergebiete",
        "order_details": "Auftragspositionen",
        "orders": "Bestellungen",
        "products": "Produkte",
        "region": "Regionen",
        "shippers": "Versandunternehmen",
        "suppliers": "Lieferanten",
        "territories": "Verkaufsgebiete",
        "us_states": "US-Bundesstaaten"
    },
    "columns": {
        "categories": {
            "category_id": "Kategorie-ID",
            "category_name": "Kategoriename",
            "description": "Kategoriebeschreibung",
            "picture": "Kategoriebild"
        },
        "customer_customer_demo": {
            "customer_id": "Kunden-ID",
            "customer_type_id": "Kundentyp-ID"
        },
        "customer_demographics": {
            "customer_type_id": "Kundentyp-ID",
            "customer_desc": "Demografische Beschreibung"
        },
        "customers": {
            "customer_id": "Kunden-ID",
            "company_name": "Firmenname",
            "contact_name": "Name des Hauptansprechpartners",
            "contact_title": "Berufsbezeichnung des Ansprechpartners",
            "address": "Straßenadresse",
            "city": "Stadt",
            "region": "Bundesland / Region",
            "postal_code": "Postleitzahl",
            "country": "Land",
            "phone": "Telefonnummer",
            "fax": "Faxnummer"
        },
        "employees": {
            "employee_id": "Mitarbeiter-ID",
            "last_name": "Nachname",
            "first_name": "Vorname",
            "title": "Berufsbezeichnung",
            "title_of_courtesy": "Höflichkeitsanrede",
            "birth_date": "Geburtsdatum",
            "hire_date": "Einstellungsdatum",
            "address": "Straßenadresse",
            "city": "Stadt",
            "region": "Bundesland / Region",
            "postal_code": "Postleitzahl",
            "country": "Land",
            "home_phone": "Telefon (privat)",
            "extension": "Telefon-Durchwahl",
            "photo": "Mitarbeiterfoto",
            "notes": "Notizen",
            "reports_to": "Berichtet an",
            "photo_path": "Pfad zur Fotodatei"
        },
        "employee_territories": {
            "employee_id": "Mitarbeiter-ID",
            "territory_id": "Gebiets-ID"
        },
        "order_details": {
            "order_id": "Bestell-ID",
            "product_id": "Produkt-ID",
            "unit_price": "Stückpreis",
            "quantity": "Bestellte Menge",
            "discount": "Rabattprozentsatz"
        },
        "orders": {
            "order_id": "Bestell-ID",
            "customer_id": "Kunden-ID",
            "employee_id": "ID des Vertriebsmitarbeiters",
            "order_date": "Bestelldatum",
            "required_date": "Erforderliches Lieferdatum",
            "shipped_date": "Versanddatum",
            "ship_via": "Versand über (Versanddienst-ID)",
            "freight": "Versandkosten",
            "ship_name": "Name des Empfängers",
            "ship_address": "Lieferadresse",
            "ship_city": "Lieferstadt",
            "ship_region": "Liefer-Bundesland / -Region",
            "ship_postal_code": "Liefer-Postleitzahl",
            "ship_country": "Lieferland"
        },
        "products": {
            "product_id": "Produkt-ID",
            "product_name": "Produktname",
            "supplier_id": "Lieferanten-ID",
            "category_id": "Kategorie-ID",
            "quantity_per_unit": "Menge pro Einheit",
            "unit_price": "Stückpreis",
            "units_in_stock": "Einheiten auf Lager",
            "units_on_order": "Einheiten in Bestellung",
            "reorder_level": "Nachbestellgrenze",
            "discontinued": "Eingestellt-Kennzeichen"
        },
        "region": {
            "region_id": "Regions-ID",
            "region_description": "Regionsbeschreibung"
        },
        "shippers": {
            "shipper_id": "Versanddienst-ID",
            "company_name": "Firmenname",
            "phone": "Telefonnummer"
        },
        "suppliers": {
            "supplier_id": "Lieferanten-ID",
            "company_name": "Firmenname",
            "contact_name": "Name des Hauptansprechpartners",
            "contact_title": "Berufsbezeichnung des Ansprechpartners",
            "address": "Straßenadresse",
            "city": "Stadt",
            "region": "Bundesland / Region",
            "postal_code": "Postleitzahl",
            "country": "Land",
            "phone": "Telefonnummer",
            "fax": "Faxnummer",
            "homepage": "Webseite"
        },
        "territories": {
            "territory_id": "Gebiets-ID",
            "territory_description": "Gebietsbeschreibung",
            "region_id": "Regions-ID"
        },
        "us_states": {
            "state_id": "Bundesstaaten-ID",
            "state_name": "Name des Bundesstaates",
            "state_abbr": "Abkürzung des Bundesstaates",
            "state_region": "Volkszählungsregion"
        }
    }
}
}

# {
#     "connectionInfo": {
#         "type": "postgres",
#         "host": "localhost",
#         "port": "5432",
#         "username": "myuser",
#         "password": "mypass",
#         "database": "fussballdb",
#         "schema": "public"
#     }
# }

###
GET http://localhost:3333/api/generation/generate

{
	"connectionInfo": {
		"type": "postgres",
		"host": "localhost",
		"port": "5432",
		"username": "myuser",
		"password": "mypass",
		"database": "fussballdb",
		"schema": "public"
	},
	"taskConfiguration": {
		"aggregation": false,
		"columnCount": 2,
		"predicateCount": 2,
		"operationTypes": [],
		"joinDepth": 2,
		"joinTypes": [],
		"groupby": false,
		"having": false,
		"orderby": true
	}
}

###
POST http://localhost:3333/api/grading/grade
content-type: application/json

{
	"connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
	"gradingRequest": {
		"taskId": "4f7c66ed-e4e5-422e-8d6f-ef4ee3876d02",
		"studentQuery": "SELECT PROJEKT.\"PNAME\", ANG_PRO.\"ANGNR\", ANGEST.\"NAME\" FROM PROJEKT LEFT JOIN ANG_PRO ON PROJEKT.\"PNR\" = ANG_PRO.\"PNR\" LEFT OUTER JOIN ANGEST ON ANG_PRO.\"ANGNR\" = ANGEST.\"ANGNR\";",
        "referenceQuery": "SELECT * FROM PROJEKT"
	},
	"languageCode": "de"
}

###
POST http://localhost:3333/api/description/template
content-type: application/json

{
	"connectionInfo": {
        "type": "postgres",
        "host": "132.176.75.244",
        "port": "5995",
        "username": "test",
        "password": "test",
        "database": "test",
        "schema": "public"
    },
	"query": "SELECT employees.region, COUNT(employees.employee_id) FROM northwind.employees GROUP BY employees.region HAVING COUNT(employees.employee_id) > 1",
	"languageCode": "de"
}